---

- name: "Attempt to stop instance"
  ansible.builtin.include_tasks: stop_instance.yml

- name: "Remove Springboot service"
  ansible.builtin.include_tasks: remove_service.yml

- name: Remove files (only on RHEL7 and higher)
  block:
    - name: Find extra files
      ansible.builtin.find:
        paths: "{{ sbi_extra_files_src }}"
      when: sbi_extra_files_src is defined and sbi_remove_extra_files
      register: found_extra_files
      delegate_to: localhost

    - name: Find keystores
      ansible.builtin.find:
        paths: "{{ sbi_keystores_src }}"
      when: sbi_keystores_src is defined and sbi_remove_keystores
      register: found_keystores
      delegate_to: localhost

    - name: Remove extra files
      ansible.builtin.file:
        state: absent
        path: "{{ sbi_extra_files_dest }}/{{ item }}"

      loop: "{{ found_extra_files.files | map(attribute='path') | regex_replace(sbi_extra_files_src|regex_escape() +'/', '') }}"
      when: sbi_extra_files_src is defined and sbi_remove_extra_files
      become: "{{ sbi_become }}"

    - name: Remove main application folder /opt
      ansible.builtin.file:
        state: absent
        path: "{{ sbi_appbase }}"
      become: "{{ sbi_become }}"

    - name: Remove main application folder /srv
      ansible.builtin.file:
        state: absent
        path: "{{ sbi_srv_dir }}"
      become: "{{ sbi_become }}"
